#include "game.h"

static const char *const stage1_words[] = {
    "fj",
    "jf",
    "ff",
    "jj",
    "fff",
    "jjj",
    "fjjf",
    "jffj",
    "ffjj",
    "jjff",
    "f j",
    "j f",
    "fj fj",
    "jf jf",
    "ff jj",
    "fj jf",
    "jff fj"
};

static const char *const stage1_climax_words[] = {
    "jj ff",
    "ff jj",
    "f jjj",
    "fff j",
    "fj jff",
    "jff fj",
    "ff jjj",
    "jjj ff",
    "fj jf fj",
    "jf fj jf"
};

static const char *const stage2_words[] = {
    "sad",
    "fad",
    "asdf",
    "fdsa",
    "dad",
    "sass",
    "adds",
    "as df",
    "sad fad",
    "add sad",
    "sass dad",
    "asfd",
    "dfas",
    "fads",
    "sadaf"
};

static const char *const stage2_climax_words[] = {
    "asdf fdsa",
    "sad adds",
    "df asdf",
    "as df sad",
    "fads sad",
    "sass dad",
    "adds fada",
    "sad fad df",
    "asfd dfas",
    "dfas asfd"
};

static const char *const stage3_words[] = {
    "j;",
    "lj",
    "jkl;",
    ";lkj",
    "all",
    "fall",
    "flak",
    "ask",
    "j k",
    "jkl; j",
    "fall ask",
    "all;all",
    "j;k;l",
    "flask",
    "j;kj",
    ";ljk"
};

static const char *const stage3_climax_words[] = {
    "jkl; ;lkj",
    "j; k; l;",
    "all; fall",
    "fall ask;",
    "j k l ;",
    ";lkj jkl;",
    "flask; all",
    "j;kj ;ljk",
    "all;all ask",
    "jkl; fall"
};

static const char *const stage4_words[] = {
    "fr",
    "ju",
    "rty",
    "rtyu",
    "try",
    "turf",
    "trust",
    "fury",
    "truth",
    "retry",
    "rusty",
    "try turf",
    "fury rut",
    "rtyu fr",
    "trusty"
};

static const char *const stage4_climax_words[] = {
    "try fury",
    "truth retry",
    "rtyu fr",
    "try turf",
    "fury rut",
    "trusty truth",
    "retry rtyu",
    "turf fury",
    "rtyu try",
    "truth turf"
};

static const char *const stage5_words[] = {
    "qwe",
    "iop",
    "quiet",
    "power",
    "paper",
    "equip",
    "we io",
    "quote",
    "upper",
    "equip power",
    "quiet poet",
    "qwerty",
    "pipe",
    "pop quiz"
};

static const char *const stage5_climax_words[] = {
    "equip power",
    "quiet poet",
    "pop quiz",
    "qwerty pipe",
    "upper quote",
    "power equip",
    "we io qwe",
    "paper quiet",
    "quote power",
    "pipe pop"
};

static const char *const stage6_words[] = {
    "bgn",
    "gbn",
    "hjm",
    "vbn",
    "nmh",
    "ghvb",
    "bnmg",
    "hgbn",
    "human",
    "moving",
    "gaming",
    "humble",
    "magma",
    "begin",
    "hinge",
    "haven",
    "venom",
    "minimum",
    "gh nm",
    "mvn",
    "bnhg",
    "ghvb nm",
    "vbn gh",
    "magma hub",
    "moving hum",
    "gaming hub",
    "human vim",
    "gnb hmv",
    "humble moving",
    "begin moving",
    "venom human"
};

static const char *const stage6_climax_words[] = {
    "magma hub",
    "moving hum",
    "gaming hub",
    "human vim",
    "gnb hmv",
    "humble moving",
    "begin moving",
    "venom human",
    "minimum venom",
    "ghvb nm bgn"
};

static const char *const stage7_words[] = {
    "z",
    "x",
    "c",
    ",",
    ".",
    "/",
    "?",
    "zxc",
    "cxz",
    ",.",
    "./",
    "z/c",
    "m,./",
    "x.z",
    "c,/",
    "z.x,c/",
    "x/c.z",
    "c,z.x",
    "mix.z",
    "quiz?",
    "cave/z",
    "x, z.",
    "zxc?/."
};

static const char *const stage7_climax_words[] = {
    "z.x,c/",
    "x/c.z",
    "c,z.x",
    "mix.z",
    "quiz?",
    "cave/z",
    "x, z.",
    "zxc?/.",
    "z/c x.z",
    "c,/ zxc"
};

static const char *const stage8_words[] = {
    "FJ",
    "AsDf",
    "SWORD",
    "Crystal",
    "KeyMap",
    "ShiftKey",
    "Lv10",
    "HP-2",
    "Fire!",
    "Guard?",
    "Save:1",
    "Stage-8",
    "Type OK",
    "Run Fast",
    "Magic:ON",
    "No_Miss",
    "Kum-Dor",
    "A1b2C3",
    "Sword+1",
    "Gate-Open",
    "Code:405",
    "Map_Q3",
    "Run+Jump",
    "HP=Full",
    "Shift?OK",
    "Book#8",
    "Alert!",
    "Queen_1",
    "Type-Ready"
};

static const char *const stage8_climax_words[] = {
    "Magic:ON",
    "No_Miss",
    "Kum-Dor",
    "A1b2C3",
    "Sword+1",
    "Gate-Open",
    "Code:405",
    "Map_Q3",
    "Run+Jump",
    "HP=Full",
    "Shift?OK",
    "Type-Ready"
};

static const char *const stage9_words[] = {
    "405-10",
    "7/27",
    "HP=014",
    "Lv3+5",
    "100%",
    "1,024",
    "3.141",
    "9:00",
    "#2026",
    "ID-405",
    "20/20?",
    "405:027",
    "90%-10",
    "1/2=0.5",
    "X9-027",
    "No.405",
    "7,270",
    "10:20/30",
    "#09-Stage",
    "2026/07/27",
    "HP100% Lv9",
    "ID:405-2026",
    "9090-XY",
    "10 10%",
    "2026#07",
    "405/10:20",
    "No.9-HP4",
    "7:27 PM"
};

static const char *const stage9_climax_words[] = {
    "1/2=0.5",
    "X9-027",
    "No.405",
    "7,270",
    "10:20/30",
    "#09-Stage",
    "2026/07/27",
    "HP100% Lv9",
    "ID:405-2026",
    "405/10:20",
    "No.9-HP4",
    "7:27 PM"
};

static const char *const stage10_words[] = {
    "!?OK",
    "@@Gate",
    "#1Boss",
    "(OK?)",
    "RPG!",
    "Kumdor?",
    "Lv+1",
    "HP=10",
    "Final!",
    "Save?No",
    "Shift+/",
    "QWERTY!",
    "KUM-405",
    "Type:OK!",
    "Sword#10",
    "(Stage10)",
    "No_Miss!",
    "A1! b2?",
    "Kumdor_01",
    "HP=10/10",
    "Lv+1 OK",
    "Final-Boss!"
};

static const char *const stage10_climax_words[] = {
    "Shift+/",
    "QWERTY!",
    "KUM-405",
    "Type:OK!",
    "Sword#10",
    "(Stage10)",
    "No_Miss!",
    "A1! b2?",
    "Kumdor_01",
    "HP=10/10",
    "Lv+1 OK",
    "Final-Boss!"
};

static const Stage stages[] = {
    {
        {"クムドールの影", 10, 10, 1, ENEMY_TRAIT_STANDARD},
        "アズドフ村の墜落跡",
        "船の残骸から這い出すと、村人たちは遠巻きにこちらを見ていた。抜け落ちたキーを探す前に、黒い影が足元から立ち上がる。",
        "ホームポジション: f / j / スペース",
        "左右の人差し指をfとjに置き、右親指でスペースを押す。",
        "「足元を見るな。指先だけで、わたしを裂いてみろ」",
        stage1_words,
        (int)(sizeof(stage1_words) / sizeof(stage1_words[0])),
        "クムドールの影が足元で二つに割れ、左右の指を同時に惑わせてくる。",
        stage1_climax_words,
        (int)(sizeof(stage1_climax_words) / sizeof(stage1_climax_words[0])),
        "おにぎり",
        2,
        2,
        "影がほどけ、村長は北へ続く道を指した。墜落で散らばったスパイスの一部も戻り、村人たちの疑いは少しだけ薄れる。まずは左手のキーを取り戻さなければならない。"
    },
    {
        {"左手の番人", 10, 10, 2, ENEMY_TRAIT_HEAVY_COUNTER},
        "アズドフ東の石畳",
        "石化したクムの木が道をふさぎ、古い門柱だけがかろうじて残っている。左手の番人が、通行料の代わりに正確な打鍵を求めた。",
        "左手ホーム段: a / s / d / f",
        "左手の指をa s d fに置き、打ったあと位置を崩さない。",
        "「左手の迷いは、門を閉ざす音になる」",
        stage2_words,
        (int)(sizeof(stage2_words) / sizeof(stage2_words[0])),
        "左手の番人が門柱を叩き、a s d fの並びを速く刻み始めた。",
        stage2_climax_words,
        (int)(sizeof(stage2_climax_words) / sizeof(stage2_climax_words[0])),
        "砲丸豆",
        2,
        3,
        "門柱のくぼみからa、s、dの感覚が戻った。石畳に刻まれていた古い案内文字が浮かび上がり、ジュクルン村への近道を示す。東へ向かう足取りが少し軽くなる。"
    },
    {
        {"右手の番人", 10, 10, 2, ENEMY_TRAIT_BLIND_EDGE},
        "ジュクルン村の鐘楼",
        "村の鐘は鳴らない。通信塔から落ちた金属片が鐘楼に刺さり、右手の番人がその下で目を光らせている。",
        "右手ホーム段: j / k / l / ;",
        "右手の指をj k l ;に置き、セミコロンまで小指で覚える。",
        "「鐘は鳴らぬ。鳴らすのは、おまえの右手だ」",
        stage3_words,
        (int)(sizeof(stage3_words) / sizeof(stage3_words[0])),
        "右手の番人が鐘楼の影を揺らし、セミコロンを混ぜた構えに変えた。",
        stage3_climax_words,
        (int)(sizeof(stage3_climax_words) / sizeof(stage3_climax_words[0])),
        "水中パン",
        2,
        3,
        "鐘楼が低く鳴り、j、k、l、;の列が指先に戻った。止まっていた村の掲示板にも通信塔の断片的な警告が流れ始める。村人は湖底へ抜ける古い道を教えてくれた。"
    },
    {
        {"湖底の影", 10, 10, 2, ENEMY_TRAIT_REGEN_COUNTER},
        "ミルファ湖の沈んだ桟橋",
        "湖面は凍っていないのに、底だけが青白く固まっている。沈んだ桟橋の影から、上段へ伸びる指を狙うものが現れた。",
        "人差し指の上段: r / t / y / u",
        "fとjから人差し指を伸ばして打ち、すぐホームに戻す。",
        "「水面が揺れた時、戻る場所を忘れるな」",
        stage4_words,
        (int)(sizeof(stage4_words) / sizeof(stage4_words[0])),
        "湖底の影が水面を波立たせ、r t y uを続けて打たせる流れを作った。",
        stage4_climax_words,
        (int)(sizeof(stage4_climax_words) / sizeof(stage4_climax_words[0])),
        "クムの実",
        3,
        4,
        "湖底に細い水路が開き、王都の方角へ流れが戻った。水に沈んだ桟橋の下から、クム3号の航行ログも見つかる。濁った水の奥でクムの実がひとつ光っている。"
    },
    {
        {"上段の魔術師", 10, 10, 3, ENEMY_TRAIT_POISON_EDGE},
        "クムの森の入口",
        "森の木々は灰色に固まり、葉の代わりに文字の欠片を落としている。上段の魔術師は枝先から課題をばらまいた。",
        "上段の広がり: q / w / e / i / o / p",
        "小指・薬指・中指を上段へ伸ばし、戻る位置を意識する。",
        "「枝先の文字は逃げる。追うなら正確に追え」",
        stage5_words,
        (int)(sizeof(stage5_words) / sizeof(stage5_words[0])),
        "上段の魔術師が枝先の文字を束ね、上段を広く使う呪文に変えた。",
        stage5_climax_words,
        (int)(sizeof(stage5_climax_words) / sizeof(stage5_climax_words[0])),
        "空気アメ",
        3,
        4,
        "石の枝に小さな緑が戻った。落ちていた文字の欠片は、誰かが通信塔から呪文を送っている証拠だった。森の奥から、王都の通信塔が発するかすかな断続音が聞こえる。"
    },
    {
        {"溶岩の番人", 10, 10, 3, ENEMY_TRAIT_HEAVY_COUNTER},
        "ズロワノフ通路跡",
        "森を抜けると、地面の裂け目に赤い光が走っていた。かつて星間航路を支えた通路跡で、溶岩の番人が中央列を守っている。",
        "中央から下段: g / h / v / b / n / m",
        "人差し指の担当範囲を広げ、左右の境目を覚える。",
        "「熱に急かされるな。境目を越える指だけが通れる」",
        stage6_words,
        (int)(sizeof(stage6_words) / sizeof(stage6_words[0])),
        "溶岩の番人が通路を赤く染め、中央から下段まで続く重い課題を押し出した。",
        stage6_climax_words,
        (int)(sizeof(stage6_climax_words) / sizeof(stage6_climax_words[0])),
        "星チーズ",
        3,
        5,
        "裂け目の熱が静まり、失われた推進装置の記録が浮かび上がった。クム3号は着陸直前に外部から入力を上書きされている。墜落は事故ではなかった。"
    },
    {
        {"水晶洞の幻", 10, 10, 3, ENEMY_TRAIT_BLIND_EDGE},
        "ケムリ苔の水晶洞",
        "熱病を鎮めるケムリ苔は、水晶の中に閉じ込められていた。洞窟の幻は下段と記号の揺さぶりで集中を奪いにくる。",
        "下段と記号: z / x / c / , / . / slash / ?",
        "下段と記号を続けて打っても、打ったあとホームへ戻す。",
        "「水晶は手元を映さない。記号の影だけを読め」",
        stage7_words,
        (int)(sizeof(stage7_words) / sizeof(stage7_words[0])),
        "水晶洞の幻が記号を反射させ、下段と記号が入り混じる構えになった。",
        stage7_climax_words,
        (int)(sizeof(stage7_climax_words) / sizeof(stage7_climax_words[0])),
        "着色タラコ",
        4,
        5,
        "水晶が砕け、ケムリ苔が息を吹き返した。洞窟の奥では、薬を待つソルフェスへの発送箱が止まったまま並んでいる。ソルフェスへ送る薬も、王都を救う手がかりも手に入った。"
    },
    {
        {"古文書の魔術師", 10, 10, 3, ENEMY_TRAIT_POISON_EDGE},
        "王立図書庫の地下",
        "王都クミエルの地下には、古いキーボード術の記録が眠っていた。古文書の魔術師は大文字と記号で封印を重ねる。",
        "総合練習: 大文字・小文字・記号",
        "速さより正確さを優先し、Shiftや記号も落ち着いて打つ。",
        "「古い封印は、ひとつの大小の違いも見逃さない」",
        stage8_words,
        (int)(sizeof(stage8_words) / sizeof(stage8_words[0])),
        "古文書の魔術師がページをめくり、大文字、数字、記号を重ねた封印を開いた。",
        stage8_climax_words,
        (int)(sizeof(stage8_climax_words) / sizeof(stage8_climax_words[0])),
        "3色ダンゴ",
        4,
        6,
        "封印の一枚が剥がれ、古文書はクムドールの剣が文字を正すための道具だったと示した。石化の中心は王城ではない。通信塔の頂上に、最後の入力源がある。"
    },
    {
        {"数字の壁", 10, 10, 4, ENEMY_TRAIT_REGEN_COUNTER},
        "クミエル通信塔",
        "塔の壁面には、墜落直前に見た数字列が焼き付いていた。数字の壁は、入力順をひとつでも誤れば階段を消してしまう。",
        "数字キーと記号: 数字列 / - / slash / % / :",
        "数字段を打ったあとホームへ戻し、記号との切り替えで焦らない。",
        "「数字は嘘をつかない。だが順番を誤れば道は消える」",
        stage9_words,
        (int)(sizeof(stage9_words) / sizeof(stage9_words[0])),
        "数字の壁が座標を組み替え、数字と記号の長い列で階段を隠した。",
        stage9_climax_words,
        (int)(sizeof(stage9_climax_words) / sizeof(stage9_climax_words[0])),
        "健康ドリンク",
        4,
        6,
        "数字列が整列し、塔の上層へ続く扉が開いた。墜落時に乱れた計器の数字も、正しい座標へ戻っていく。そこにはクムドールの剣を封じた最後の試練が待っている。"
    },
    {
        {"クムドールの試練", 10, 10, 4, ENEMY_TRAIT_HEAVY_COUNTER},
        "通信塔最上階",
        "塔の最上階で、抜け落ちたすべてのキーが剣の形に並ぶ。クムドールの試練は、これまで覚えたすべての打鍵を求めてきた。",
        "最終練習: Shift記号と混合課題",
        "Shift、大文字、数字、記号、スペースを正確に切り替える。",
        "「すべてのキーを取り戻すなら、最後まで目を逸らすな」",
        stage10_words,
        (int)(sizeof(stage10_words) / sizeof(stage10_words[0])),
        "クムドールの試練が剣の形に光り、これまでのすべての打鍵を一息で求めてきた。",
        stage10_climax_words,
        (int)(sizeof(stage10_climax_words) / sizeof(stage10_climax_words[0])),
        "立喰いソバ",
        10,
        8,
        "剣はあなたの入力に応え、石化の呪文を一文字ずつ上書きしていく。抜け落ちていたキーはすべて元の場所へ戻り、塔の外で森がざわめき始めた。"
    }
};

const Stage *get_stages(int *stage_count) {
    *stage_count = (int)(sizeof(stages) / sizeof(stages[0]));
    return stages;
}
